### ISSUE TITLE
Error mhash

### ISSUE THREAD

**Issue by rammos92** [Pymmdrza/RichWalletPrivateKeyFinder2#1]
ImportError: cannot import name 'mHash' from 'hexer' (/home/dell/.local/lib/python3.9/site-packages/hexer/__init__.py)

**Comment by rammos92** [comment]
i use the hexer.py of the old version

**Comment by Pymmdrza** [comment]
https://github.com/Pymmdrza/RichWalletPrivateKeyFinder2/blob/mainx/hexer.py

**Comment by Pymmdrza** [comment]
> i use the hexer.py of the old version

https://github.com/Pymmdrza/RichWalletPrivateKeyFinder2/blob/mainx/hexer.py
