### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'eth500.txt'

### ISSUE THREAD

**Issue by hackerxx360** [Pymmdrza/RichWalletPrivateKeyFinder2#7]
FileNotFoundError: [Errno 2] No such file or directory: 'eth500.txt'

**Comment by Pymmdrza** [comment]
You are so easygoing and don't bother to search a little 

[.](https://github.com/Pymmdrza/Rich-Address-Wallet)

> FileNotFoundError: [Errno 2] No such file or directory: 'eth500.txt'
